// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Todo struct {
	ID          string
	UserID      int32
	Title       string
	Description pgtype.Text
	Completed   bool
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}
